### PR TITLE
add note on moving/renaming paths

### LINKED ISSUE #150: Renaming a directory in a deeply nested path while executing a rename on a file will create a new nested directory if it doesn't exist
If you rename a file that's in a nested directory and you decide to rename one of the nested directories to a name that doesn't exist yet, it will create a new directory instead of renaming the existing directory and your renamed file (even if the file name didn't change) will get located there.

Reproducible steps on Vim 8.1 using the latest master commit as of this issue's date:

1. Create a test file in a deeply nested directory:

```
mkdir -p /tmp/testfern/foo/bar/baz \
  && cd /tmp/testfern \
  && touch foo/bar/baz/hello
```

2. Open Vim with `vim .`

3. Open the `hello` file with `:e foo/bar/baz/hello`

4. Toggle and reveal `hello` in fern

5. Execute `fern-action-move` on `hello`

6. Notice how fern is asking you to rename the `hello` file

7.  Rename `foo` to `foo2` in the destination path and but the leave the file name alone

You will end up with `tmp/testfern/foo2/bar/baz/hello` and `/tmp/testfern/foo/bar/baz` will be empty. The file was moved to a new directory instead of the existing `foo` directory being renamed to `foo2`.

I'll admit, I'm not 100% on what the expected behavior should be here. Personally I feel like it should probably rename the existing directory to `foo2` without creating a new one. It's worth bringing up that if both `foo` and `foo2` directories exist beforehand it will move the file between them as expected.

### PR DESCRIPTION
**Pull request by thisguychris**
- move/rename only affects tail nodes.
- add warning tag
- fixes #150

### CODE REVIEW

**Comment by lambdalisue** [comment]
As commented in https://github.com/lambdalisue/fern.vim/issues/150#issuecomment-670836738, I'll probably reject this PR sorry.

**Comment by thisguychris** [comment]
hey, @lambdalisue no problem. I just added the warning tag, because that's how @bluz71 [phrased it](https://github.com/lambdalisue/fern.vim/issues/150#issuecomment-669597458). Personally I think what we have in the doc suffice because that's how I understand `mv` works. However, there are cases where people misunderstood the behavior like #150.

Another approach would be adding a note that `fern-action-move` is just doing a native `mv` plus a `mkdir -p` if the folder does not exist. As @nickjj mentioned that he wanted more magic (like deciding to moving the actual folder) since it's already doing an additional operation if we compare it to native `mv`.

**Comment by nickjj** [comment]
I'd consider re-wording that because the current `WARNING: Moving/Renaming only affects tail nodes.` makes it seem like the move / rename commands won't allow you to change a directory that a file is in because you can only modify tail nodes. Meaning, based on that warning I read that as it's impossible to select a file and move it to a directory that exists.

**Comment by thisguychris** [comment]
@nickjj is this more clear for you?

**Comment by nickjj** [comment]
Yep but I would consider changing `directories` to `parent directories`.

**Comment by thisguychris** [comment]
@nickjj added, thanks for the help. 👌

@lambdalisue I've rebased the extra commits and merged into one commit based on @nickjj feedback. Feel free to close this `PR` if you don't feel the need to update. ✌

**Comment by lambdalisue** [comment]
I'm sorry but I feel it's too much. If I accept it, I cannot reject "I don't understand the 'copy' action, the documentation should have "This action is like cp command in Unix." or whatever and it's kind endless.

**Pull request closed without merging**
