### PR TITLE
fix: fnameescape args for ex action

### PR DESCRIPTION
**Pull request by tomtomjhj**

### CODE REVIEW

**Comment by lambdalisue** [comment]
Why?

**Comment by tomtomjhj** [comment]
Path name may contain special chars like space, %, +, etc. They have special meaning in the context of many ex commands (e.g. % gets expanded). So we should fnameescape it to avoid such interpretation.

btw vim-vinegar's `·` does fnameescaping too.

**Comment by lambdalisue** [comment]
Okay, it sounds good. However, in that case, I think there are few cases where `fnameescape` is not used, so I would like to stop tricky use of v:count and add it as a separate action if there is a demand for it. So please remove the v:count related functionality and documentation and re-implement it in a simpler form.

**Comment by tomtomjhj** [comment]
fixed as suggested

**Review by lambdalisue — APPROVED** [review]

**Pull request merged**
