### PR TITLE
Add `g:fern#window_selector_use_popup` to use popup/float window when select window.

### PR DESCRIPTION
**Pull request by skanehira**

### CODE REVIEW

**Review by lambdalisue — CHANGES_REQUESTED** [review]
Please properly update vital module (`Vitalize .`)

**Comment by skanehira** [comment]
@lambdalisue Already executed

**Comment by lambdalisue** [comment]
? Then why https://github.com/lambdalisue/fern.vim/blob/main/autoload/vital/fern.vital is not updated???

**Comment by skanehira** [comment]
I updated `vital.vim` and ran `:Vitalize .` again, and the hash in `vital/fern.vital` is updated, but do I need to update `vital.vim`?
I don't know why `vital.vim` is need to update, but If need, I'll update PR.

**Comment by lambdalisue** [comment]
> I updated vital.vim and ran :Vitalize . again, and the hash in vital/fern.vital is updated, but do I need to update vital.vim?
I don't know why vital.vim is need to update, but If need, I'll update PR.

Oh, my bad. I might drunk. This update is for vital-Whisky mean that `fern.vital` should NOT be updated :bow:

**Review by lambdalisue — APPROVED** [review]
LGTM

**Pull request merged**
