### PR TITLE
Add "enter-to-leave" on root node feature by default

### LINKED ISSUE #496: Add a way to go up a directory with `Return`
image

> Pretty much every “graphical” file explorer has a graphical option to go one level-up and there is a reason why: for people who use arrows to move between files/folders and hit Enter to get into a folder it would be natural by continuity to stay in the setup arrow+enter also to go one level up. They don’t have to change position on the keyboard and the brain avoid a context switch which is very good. Having a mechanism to go into a folder and be forced to switch mechanics to go out is in general not a good idea.

https://github.com/lambdalisue/fern.vim/issues/119#issuecomment-1990913270

Personally, I thought it was unnecessary, but after the explanation above, I understand. I probably will make it so that it can be displayed with some kind of option.

### PR DESCRIPTION
**Pull request by lambdalisue**
Close #496

## Summary by CodeRabbit

- **New Features**
	- Introduced a new configuration option to control the "enter to leave" behavior on the root node of the tree, enhancing navigation flexibility.

- **Documentation**
	- Documented the addition of a global variable for controlling tree navigation behavior.

### CODE REVIEW

**Comment by ubaldot** [comment]
I gave it a shot but for some reason it does not work on MacVim. I posted a small video, see below. 

https://github.com/lambdalisue/fern.vim/assets/10845685/abdf6c45-19f3-415b-a4a8-51b2d1bffd52

**Comment by lambdalisue** [comment]
I didn't recall what the default was, but it seems your `<CR>` is remapped to the `expand` action. What this pull request changed is the behavior of the `enter` action. So the expected behavior is something like:

https://github.com/lambdalisue/fern.vim/assets/546312/740ea1f9-35b8-4c50-a899-a611d8e67b62

Is your desired behavior "Expand the branch node with `Enter` and go up to the root node with `Enter`"? Is that correct?

**Comment by ubaldot** [comment]
> Is your desired behavior "Expand the branch node with `Enter` and go up to the root node with `Enter`"? Is that correct?
 
Yes, exactly. For changing dire I have the following mapping: 

` nmap <buffer><nowait> cd <Plug>(fern-action-enter)<Plug>(fern-action-cd:cursor)<Cmd>pwd<cr>`

**Comment by lambdalisue** [comment]
@ubaldot Got it. While everyone has different preferences, I think we should add a smart mapping helper function instead. Could you try https://github.com/lambdalisue/fern.vim/pull/498 and see if that addresses your desired behavior?

**Pull request closed without merging**
