### PR TITLE
Stop insert mode after jump to fern UI

### PR DESCRIPTION
**Pull request by przepompownia**

### CODE REVIEW

**Comment by lambdalisue** [comment]
What?

**Comment by przepompownia** [comment]
Exactly as this autocommand says. Without this autocommand I need to leave insert mode manually after jump to fern window.

**Comment by lambdalisue** [comment]
> Without this autocommand I need to leave insert mode manually after jump to fern window.

I guess that's your configuration issue while fern itself does not touch mode. 

I'm sorry but I'm not going to accept this unless the situation is caused by fern feature.

**Comment by przepompownia** [comment]
I have defined keymaps to switch between windows in insert mode. After switching in this way I get messages about trying to change unmodifable buffer. 

There is no problem to add this autocommand to my local configuration. Thanks for quick response.

**Pull request closed without merging**
